### ISSUE TITLE
twofing seems capable of entering endless loops

### ISSUE THREAD

**Issue by mgrouch** [Plippo/twofing#11]
twofing seems capable of entering endless loops

I see CPU constantly at 25% consumed by twofing.

Thanks,
--MG

**Comment by mgrouch** [comment]
it is looping after select() call.

**Comment by Plippo** [comment]
Thank you, this bug should now be fixed. Please verify that it is also fixed for you with the recent change.

**Comment by mgrouch** [comment]
Thanks. Works now.
