### ISSUE TITLE
Please make new release on github

### ISSUE THREAD

**Issue by jonesmz** [Plippo/twofing#14]
I work on a linux distribution focusing on the raspberry pi, which packages the twofing project as an installable package.
See package here: https://github.com/GenPi64/genpi64-overlay/blob/master/x11-misc/twofing/twofing-0.1.2-r2.ebuild

Turns out we're about a decade out of date.

Can you make a new release here on github? Either a tag in git, or using the github "Releases" feature?
That would enable us to update our package to the newest version easily. We're reluctant to do direct git checkouts for a specific commit.

**Comment by Plippo** [comment]
Thank you for your suggestion. The project has been pretty stable (one could also say unmaintained) during the last years, but I know a lot of people (including myself) are using it and there have been some small fixes/additions from time to time.
As proposed, I created a release using github’s feature: https://github.com/Plippo/twofing/releases/tag/v0.1.6
