### ISSUE TITLE
twofing not working correctly in RPi 4 + Raspad

### ISSUE THREAD

**Issue by lee-yunseok** [Plippo/twofing#6]
I'm using Raspberry Pi 4(64bit RasPi OS) with [Raspad 3](https://raspad.com/products/raspadv3).

In my environment, twofing only works with web-browser. How to make it work anywhere?

**Comment by Plippo** [comment]
I have unfortunately no idea what software this device uses. twofing turns your touch input into mouse and keyboard events. If the software does not react to these events, it won't work. E.g. if you can use a mouse wheel to scroll in those apps, you should also be able to scroll with twofing. If not, then not.
